CircuitDev192/Game3

Assets/Prefabs/Weapons/SA_Wep_AssaultRifle01.prefab, Assets/Prefabs/Weapons/SA_Wep_DesertEagle.prefab, Assets/Prefabs/Weapons/SA_Wep_SpazShotgun.prefab
Changed the weapon sounds from 3D to 2D so the gun sounds do not only come out of the right earphone. Closes #22
=> Weapon Sound Origin Change

Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponFireState.cs
Fixed "bug" where guns would not reload after mag was emptied. closes #25
=> Issue25 automatic reloads

Assets/Prefabs/Zombies/SA_Zombie_AirportSecurity.prefab, Assets/Prefabs/Zombies/SA_Zombie_AirportWorker.prefab, Assets/Prefabs/Zombies/SA_Zombie_Bellhop.prefab, Assets/Prefabs/Zombies/SA_Zombie_Businessman.prefab, Assets/Prefabs/Zombies/SA_Zombie_Cheerleader.prefab, Assets/Prefabs/Zombies/SA_Zombie_Farmer.prefab, Assets/Prefabs/Zombies/SA_Zombie_FarmersDaughter.prefab, Assets/Prefabs/Zombies/SA_Zombie_Firefighter.prefab, Assets/Prefabs/Zombies/SA_Zombie_FootballPlayer.prefab, Assets/Prefabs/Zombies/SA_Zombie_Hobo.prefab, Assets/Prefabs/Zombies/SA_Zombie_Industrial.prefab, Assets/Prefabs/Zombies/SA_Zombie_Mechanic.prefab, Assets/Prefabs/Zombies/SA_Zombie_Mountie.prefab, Assets/Prefabs/Zombies/SA_Zombie_Pilot.prefab, Assets/Prefabs/Zombies/SA_Zombie_Pimp.prefab, Assets/Prefabs/Zombies/SA_Zombie_Prisoner.prefab, Assets/Prefabs/Zombies/SA_Zombie_Prostitute.prefab, Assets/Prefabs/Zombies/SA_Zombie_Roadworker.prefab, Assets/Prefabs/Zombies/SA_Zombie_Robber.prefab, Assets/Prefabs/Zombies/SA_Zombie_Runner.prefab, Assets/Prefabs/Zombies/SA_Zombie_Shopkeeper.prefab, Assets/Prefabs/Zombies/SA_Zombie_Soldier.prefab, Assets/Prefabs/Zombies/SA_Zombie_Streetman.prefab, Assets/Prefabs/Zombies/SA_Zombie_Tourist.prefab, Assets/Prefabs/Zombies/SA_Zombie_Trucker.prefab, Assets/Scripts/ZombieScripts/Zombie States/ZombieContext.cs
=> Randomized Zombie Pitches

Assets/Materials.meta, Assets/Materials/Sand.mat, Assets/Materials/Sand.mat.meta, Assets/Prefabs/FPSController.prefab, Assets/Standard Assets/Environment/Water/Water/Materials/WaterProNighttime.mat, Assets/Standard Assets/Environment/Water/Water4/Materials/Water4Advanced.mat, ProjectSettings/QualitySettings.asset
A beach has been added around the other 3 sides of the map, with Unity's standard 'advanced' water surrounding the island. Also, various improvements have been made, such as removing floating objects, and roads that lead to nowhere.
Closes #40 
Closes #43
=> Map Improvements and Water

Assets/Scripts/FirstPersonMovement.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimRun.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimWalk.cs
Fixes bug where pressing space in midair will cause another jump on landing
Fixes bug/oversight where player can sprint backwards and sideways
Closes #34 and #37
=> Fix of buffered jump and backwards sprinting bugs

Assets/Prefabs/UI/GameUI.prefab, Assets/Prefabs/Weapons/SA_Wep_AssaultRifle01.prefab, Assets/Prefabs/Weapons/SA_Wep_AssaultRifle02.prefab, Assets/Prefabs/Weapons/SA_Wep_DesertEagle.prefab, Assets/Prefabs/Weapons/SA_Wep_Pistol.prefab, Assets/Prefabs/Weapons/SA_Wep_SpazShotgun.prefab, Assets/Scripts/Management/EventManager.cs, Assets/Scripts/Management/PlayerManager.cs, Assets/Scripts/UI/UIConsumableWheelController.cs, Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponContext.cs
=> Consumables Count Implemented

Assets/Audio/Weapon Sounds/Gun SFX Library.meta, Assets/Scripts/FirstPersonMovement.cs, Assets/Scripts/PlayerAnimScripts/PlayerAnimFSM.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimBase.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimCrouch.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimCrouch.cs.meta, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimDead.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimIdle.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimJump.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimRun.cs, Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimWalk.cs, Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponContext.cs, Assets/SimpleApocalypse/Models/Characters/Animator/SimpleCharacter_5.0.controller
Also fixed a bug where player starts with weapon lowered.
Closes #35 
Closes #71 
Closes #70
=> Converted Player Animation FSM to Generic FSM / Added Crouching

Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_AssaultRifle_Pickup_Box.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_AssaultRifle_Pickup_Magazine.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_Handgun_Pickup.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_Handgun_Pickup_Magazine.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_Shotgun_Pickup_Box.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_MedicBag_Pickup.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_Flaregun_Ammo_Pckup.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_FlashBang_Ammo_Pickup.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_FragGrenade_Ammo_Pickup.prefab, Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_Suppressor_Pickup.prefab, Assets/Prefabs/Weapons/SA_Wep_AssaultRifle01.prefab, Assets/Prefabs/Weapons/SA_Wep_AssaultRifle02.prefab, Assets/Prefabs/Weapons/SA_Wep_DesertEagle.prefab, Assets/Prefabs/Weapons/SA_Wep_Katana.prefab, Assets/Prefabs/Weapons/SA_Wep_Pistol.prefab
=> Weapon Range and Pickup Collider Fix

Assets/Scripts/LightFlickerController.cs, Assets/Scripts/LightFlickerController.cs.meta, Assets/Scripts/ZombieScripts/Zombie States/ZombieBaseState.cs, Assets/Scripts/ZombieScripts/Zombie States/ZombieFleeState.cs, Assets/SimpleApocalypse/Prefabs/Props/SA_Prop_StreetLamp_01.prefab, Assets/SimpleApocalypse/Prefabs/Props/SA_Prop_StreetLamp_Damaged_01.prefab
=> Updated street lamp prefabs.

Assets/Animations.meta, Assets/Animations/UI.meta, Assets/Animations/UI/FlashbangEffectAnim.anim, Assets/Animations/UI/FlashbangEffectAnim.anim.meta, Assets/Animations/UI/Image.controller, Assets/Animations/UI/Image.controller.meta, Assets/Materials/LitPuddle_mat.mat, Assets/Prefabs/UI/FlashbangUI.prefab, Assets/Prefabs/UI/FlashbangUI.prefab.meta, Assets/Prefabs/Weapons/Consumables/Explosion.prefab, Assets/Prefabs/Weapons/Consumables/Explosion.prefab.meta, Assets/Prefabs/Weapons/Consumables/Flare.prefab, Assets/Prefabs/Weapons/Consumables/Flare.prefab.meta, Assets/Prefabs/Weapons/Consumables/SA_Wep_Flaregun.prefab, Assets/Prefabs/Weapons/Consumables/SA_Wep_FlashBangThrown.prefab, Assets/Prefabs/Weapons/Consumables/SA_Wep_GrenadeThrown.prefab, Assets/Scripts/UI/UIFlashbangController.cs, Assets/Scripts/UI/UIFlashbangController.cs.meta, Assets/Scripts/Weapons/Consumables/FlareController.cs, Assets/Scripts/Weapons/Consumables/FlareController.cs.meta, Assets/Scripts/Weapons/Throwables/Flashbang.cs, Assets/Scripts/Weapons/Throwables/FragGrenade.cs, Assets/VFX/Explosion.vfx, Assets/VFX/Explosion.vfx.meta, Assets/VFX/Fire.vfx, Assets/VFX/Flare.vfx, Assets/VFX/Flare.vfx.meta, ProjectSettings/ProjectSettings.asset
=> Frags, Flashes, and Flares

Assets/Scripts/FirstPersonMovement.cs, Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponFireState.cs, Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponIdleState.cs, Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponSwapState.cs
Player can no longer shoot while sprinting. Crouching will no longer make noise for zombies. When picking up a weapon, the flashlight will now stay on if it was on before picking up the weapon.
=> Resolved issues 76, 84, and 27

Assets/Prefabs/Missions/Mission1.prefab, Assets/Prefabs/Missions/Mission2.prefab, Assets/Prefabs/Missions/Mission2.prefab.meta, Assets/Scripts/Management/EventManager.cs, Assets/Scripts/Management/MissionManager.cs, Assets/Scripts/Missions/Mission1.cs, Assets/Scripts/NPCController.cs, Assets/Scripts/NPCController.cs.meta, Assets/Scripts/UI/UIMissionDialogController.cs, Assets/Scripts/UI/UIMissionDialogController.cs.meta
NPC will give the player each mission. Between missions, the player is free to explore the world.
=> Mission Giver NPC Done

Assets/Prefabs/Environment/Weather Tile.prefab, Assets/Prefabs/Environment/Weather Tile.prefab.meta, Assets/Prefabs/NPC.prefab, Assets/Prefabs/NPC.prefab.meta, Assets/Prefabs/UI/GameUI.prefab, Assets/Scripts/Weapons/Consumables/FlareController.cs, Assets/VFX/Flare.vfx
=> Flares have trails when you shoot them now.

Assets/Materials/LitOcean_mat.mat, Assets/Materials/Sand.mat, Assets/Prefabs/Weapons/Consumables/SA_Prop_RockThrown.prefab, Assets/Prefabs/Weapons/Consumables/SA_Wep_FlashBangThrown.prefab, Assets/Prefabs/Weapons/Consumables/SA_Wep_GrenadeThrown.prefab, Assets/Scripts/Management/WeatherManager.cs, Assets/VFX/Rain Splash.vfx
=> Added lightning and thunder sounds. Also lightning flash.

Assets/Scenes/Main Menu.unity, Assets/Scripts/UI/UIMainMenuController.cs, Assets/Scripts/UI/UIMainMenuController.cs.meta
It says the title, it has buttons! It's incredible!
Closes #124
=> Added main menu

Assets/Scripts/Management/PlayerManager.cs
=> Fixed where consumables now show correct ammo count

.gitignore, Assets/Scripts/UI/UIPlayerInfoController.cs, Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponIdleState.cs
Closes #118 and #21 
number keys > scroll wheel
=> Number Keys and Ammo Pickup Fix

Assets/Animations/UI/FadeToFromBlack.controller, Assets/Animations/UI/FadeToFromBlack.controller.meta, Assets/Animations/UI/FadeToFromBlackAnim.anim, Assets/Animations/UI/FadeToFromBlackAnim.anim.meta, Assets/Animations/UI/HoldBlack.anim, Assets/Animations/UI/HoldBlack.anim.meta, Assets/Animations/UI/HoldClear.anim, Assets/Animations/UI/HoldClear.anim.meta, Assets/Prefabs/BlackhawkHeli.prefab, Assets/Scripts/CutsceneNPCController.cs, Assets/Scripts/HelicopterController.cs, Assets/Scripts/Management/EndingSequenceManager.cs, Assets/Scripts/Management/EventManager.cs, Assets/Scripts/Management/GameManager.cs, Assets/Scripts/UI/UICreditsController.cs, Assets/Scripts/UI/UICreditsController.cs.meta, Assets/Scripts/UI/UIEndSequenceController.cs, Assets/Scripts/UI/UIEndSequenceController.cs.meta, Assets/VFX/Explosion.vfx, ProjectSettings/EditorBuildSettings.asset
Credits will be added later. shouldnt be a hard addition.
Closes #101
=> Ending Cutscene Added

Assets/Prefabs/Missions/Mission3.prefab, Assets/Prefabs/UI/GameUI.prefab, Assets/Scripts/DustCloudController.cs, Assets/Scripts/PoliceStationNPCController.cs, Assets/Scripts/PoliceStationNPCController.cs.meta, Assets/SimpleApocalypse/Prefabs/Props/SA_Prop_SecurityWallGate_01.prefab, Assets/VFX/Dust Cloud.vfx
Map is a bit more dynamic now, with lights and fires. NPCs are now populing the police station. Helicopters can now throw up dust if they a certain distance above ground, and mission 3 was made a bit easier. Colliders and UI elements that should not be raycast targets have been fixed.
=> Map improvements, NPCs, and more

Assets/Scenes/Main Menu.unity, Assets/Scripts/Management/MissionData.cs, Assets/Scripts/Management/MissionData.cs.meta, Assets/Scripts/Management/MissionManager.cs, Assets/Scripts/Management/SaveManager.cs, Assets/Scripts/Management/SaveManager.cs.meta, Assets/Scripts/UI/UIMainMenuController.cs, ProjectSettings/EditorBuildSettings.asset
Also, a cheat button to skip to mission 5, and a reset button have been added to the main menu!
=> Saving and Loading!

Assets/Prefabs/Blood Splatter (Enhanced).prefab, Assets/Prefabs/Blood Splatter (Enhanced).prefab.meta, Assets/Prefabs/Hit Sparks (Enhanced).prefab, Assets/Prefabs/Hit Sparks (Enhanced).prefab.meta, Assets/Prefabs/Weapons/SA_Wep_AssaultRifle01.prefab, Assets/Prefabs/Weapons/SA_Wep_AssaultRifle02.prefab, Assets/Prefabs/Weapons/SA_Wep_DesertEagle.prefab, Assets/Prefabs/Weapons/SA_Wep_Katana.prefab, Assets/Prefabs/Weapons/SA_Wep_Pistol.prefab, Assets/Prefabs/Weapons/SA_Wep_SpazShotgun.prefab, Assets/Standard Assets/ParticleSystems/Textures/SplashesLargeParticle.png.meta, Assets/VFX/BloodSplatter.vfx, Assets/VFX/BloodSplatter.vfx.meta, Assets/VFX/Hit Sparks.vfx, Assets/VFX/Hit Sparks.vfx.meta, Assets/VFX/Super Sparks.vfx, Assets/VFX/Super Sparks.vfx.meta
=> Updated the blood splatter and the bullet sparks
